-- CreateTable
CREATE TABLE "misa"."sales_detail_report" (
    "ref_detail_id" UUID NOT NULL,
    "session_id" UUID,
    "detail_id" INTEGER,
    "refid" UUID,
    "sync_session_id" UUID NOT NULL,
    "posted_date" TIMESTAMPTZ(6),
    "refdate" TIMESTAMPTZ(6),
    "inv_date" TIMESTAMPTZ(6),
    "expiry_date" TIMESTAMPTZ(6),
    "refno" TEXT,
    "inv_no" TEXT,
    "inv_series" TEXT,
    "journal_memo" TEXT,
    "description" TEXT,
    "account_object_id" UUID,
    "account_object_code" TEXT,
    "account_object_name" TEXT,
    "account_object_address" TEXT,
    "account_object_tax_code" TEXT,
    "account_object_group_list_code" TEXT,
    "account_object_group_list_name" TEXT,
    "tel" TEXT,
    "contact_name" TEXT,
    "contact_title" TEXT,
    "contact_mobile" TEXT,
    "contact_email" TEXT,
    "buyer" TEXT,
    "shipping_address" TEXT,
    "inventory_item_id" UUID,
    "inventory_item_code" TEXT,
    "inventory_item_name" TEXT,
    "inventory_item_category_code" TEXT,
    "inventory_item_category_name" TEXT,
    "inventory_item_source" TEXT,
    "inventory_item_description" TEXT,
    "is_promotion" BOOLEAN,
    "stock_code" TEXT,
    "stock_name" TEXT,
    "unit_name" TEXT,
    "main_unit_name" TEXT,
    "main_convert_rate" DECIMAL(19,4),
    "sale_quantity" DECIMAL(19,4),
    "main_quantity" DECIMAL(19,4),
    "promotion_sale_quantity" DECIMAL(19,4),
    "promotion_sale_main_quantity" DECIMAL(19,4),
    "promotion_return_quantity" DECIMAL(19,4),
    "promotion_return_main_quantity" DECIMAL(19,4),
    "not_promotion_sale_quantity" DECIMAL(19,4),
    "not_promotion_sale_main_quantity" DECIMAL(19,4),
    "not_promotion_return_quantity" DECIMAL(19,4),
    "not_promotion_return_main_quantity" DECIMAL(19,4),
    "return_quantity" DECIMAL(19,4),
    "return_main_quantity" DECIMAL(19,4),
    "panel_length_quantity" DECIMAL(19,4),
    "panel_height_quantity" DECIMAL(19,4),
    "panel_width_quantity" DECIMAL(19,4),
    "panel_radius_quantity" DECIMAL(19,4),
    "panel_quantity" DECIMAL(19,4),
    "exchange_rate" DECIMAL(19,4),
    "currency_id" TEXT,
    "unit_price_oc" DECIMAL(19,4),
    "unit_price" DECIMAL(19,4),
    "fixed_sale_unit_price" DECIMAL(19,4),
    "main_unit_price" DECIMAL(19,4),
    "cost_unit_price" DECIMAL(19,4),
    "sale_amount_oc" DECIMAL(19,4),
    "return_amount_oc" DECIMAL(19,4),
    "reduce_amount_oc" DECIMAL(19,4),
    "discount_amount_oc" DECIMAL(19,4),
    "item_discount_amount_oc" DECIMAL(19,4),
    "invoice_discount_amount_oc" DECIMAL(19,4),
    "vat_amount_oc" DECIMAL(19,4),
    "receipt_amount_oc" DECIMAL(19,4),
    "sale_amount" DECIMAL(19,4),
    "return_amount" DECIMAL(19,4),
    "reduce_amount" DECIMAL(19,4),
    "discount_amount" DECIMAL(19,4),
    "item_discount_amount" DECIMAL(19,4),
    "invoice_discount_amount" DECIMAL(19,4),
    "vat_amount" DECIMAL(19,4),
    "receipt_amount" DECIMAL(19,4),
    "cost_amount" DECIMAL(19,4),
    "export_tax_amount" DECIMAL(19,4),
    "item_discount_rate" DECIMAL(19,4),
    "invoice_discount_rate" DECIMAL(19,4),
    "debit_account" TEXT,
    "credit_account" TEXT,
    "cost_account" TEXT,
    "stock_account" TEXT,
    "discount_account" TEXT,
    "vat_account" TEXT,
    "export_tax_account" TEXT,
    "employee_code" TEXT,
    "employee_name" TEXT,
    "organization_unit_code" TEXT,
    "department_name" TEXT,
    "province_or_city" TEXT,
    "district" TEXT,
    "ward_or_commune" TEXT,
    "order_refno" TEXT,
    "contract_code" TEXT,
    "in_out_refno" TEXT,
    "other_sys_order_code" TEXT,
    "reftype" INTEGER,
    "reftype_name" TEXT,
    "branch_id" UUID,
    "branch_name" TEXT,
    "list_item_code" TEXT,
    "list_item_name" TEXT,
    "master_custom_field1" TEXT,
    "master_custom_field2" TEXT,
    "master_custom_field3" TEXT,
    "master_custom_field4" TEXT,
    "master_custom_field5" TEXT,
    "master_custom_field6" TEXT,
    "master_custom_field7" TEXT,
    "master_custom_field8" TEXT,
    "master_custom_field9" TEXT,
    "master_custom_field10" TEXT,
    "custom_field1" TEXT,
    "custom_field2" TEXT,
    "custom_field3" TEXT,
    "custom_field4" TEXT,
    "custom_field5" TEXT,
    "custom_field6" TEXT,
    "custom_field7" TEXT,
    "custom_field8" TEXT,
    "custom_field9" TEXT,
    "custom_field10" TEXT,
    "expand_field_customer1" TEXT,
    "expand_field_customer2" TEXT,
    "expand_field_customer3" TEXT,
    "expand_field_customer4" TEXT,
    "expand_field_customer5" TEXT,
    "expand_field1" TEXT,
    "expand_field2" TEXT,
    "expand_field3" TEXT,
    "expand_field4" TEXT,
    "expand_field5" TEXT,
    "channel" TEXT,
    "shop_name" TEXT,
    "shop_id" TEXT,
    "store_code" TEXT,
    "store_name" TEXT,
    "project_work_code" TEXT,
    "project_work_name" TEXT,
    "lot_no" TEXT,
    "license_plate" TEXT,
    "updated_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sales_detail_report_pkey" PRIMARY KEY ("ref_detail_id")
);

-- CreateIndex
CREATE INDEX "idx_sales_posted_date" ON "misa"."sales_detail_report"("posted_date");

-- CreateIndex
CREATE INDEX "idx_sales_refdate" ON "misa"."sales_detail_report"("refdate");

-- CreateIndex
CREATE INDEX "idx_sales_employee_code" ON "misa"."sales_detail_report"("employee_code");

-- CreateIndex
CREATE INDEX "idx_sales_inventory_item_code" ON "misa"."sales_detail_report"("inventory_item_code");

-- CreateIndex
CREATE INDEX "idx_sales_account_object_code" ON "misa"."sales_detail_report"("account_object_code");
