-- CreateTable
CREATE TABLE "erpnext"."contacts" (
    "uuid" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "owner" VARCHAR(255),
    "creation" TIMESTAMP(6),
    "modified" TIMESTAMP(6),
    "modified_by" VARCHAR(255),
    "docstatus" INTEGER,
    "idx" INTEGER,
    "salutation" VARCHAR(50),
    "first_name" VARCHAR(255),
    "address" VARCHAR(255),
    "gender" VARCHAR(20),
    "sync_with_google_contacts" INTEGER,
    "middle_name" VARCHAR(255),
    "full_name" VARCHAR(255),
    "last_name" VARCHAR(255),
    "user" VARCHAR(255),
    "inserted_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6),
    "haravan_customer_id" VARCHAR(255),
    "lead_owner" VARCHAR(255),
    "source_group" VARCHAR(255),
    "source" VARCHAR(255),
    "status" VARCHAR(50),
    "designation" VARCHAR(255),
    "phone" VARCHAR(20),
    "email_id" VARCHAR(255),
    "mobile_no" VARCHAR(20),
    "company_name" VARCHAR(255),
    "image" VARCHAR(255),
    "source_name" VARCHAR(255),
    "type" VARCHAR(50),
    "first_message_time" TIMESTAMP(6),
    "last_message_time" TIMESTAMP(6),
    "phone_number_provided_time" TIMESTAMP(6),
    "department" VARCHAR(255),
    "unsubscribed" INTEGER,
    "last_outgoing_call_time" TIMESTAMP(6),
    "last_incoming_call_time" TIMESTAMP(6),
    "last_summarize_time" TIMESTAMP(6),
    "is_replied" INTEGER,
    "pancake_conversation_id" VARCHAR(255),
    "pancake_inserted_at" TIMESTAMP(6),
    "pancake_updated_at" TIMESTAMP(6),
    "pancake_customer_id" VARCHAR(255),
    "thread_id" VARCHAR(255),
    "psid" VARCHAR(255),
    "can_inbox" INTEGER,
    "pancake_page_id" VARCHAR(255),
    "custom_uuid" VARCHAR(255),
    "page_url" VARCHAR(255),
    "user_agent" VARCHAR(255),
    "remote_ip" VARCHAR(255),
    "form_id" VARCHAR(255),
    "form_name" VARCHAR(255),
    "form_inserted_at" TIMESTAMP(6),
    "form_updated_at" TIMESTAMP(6),
    "stringee_id" VARCHAR(255),
    "stringee_to_number" VARCHAR(50),
    "stringee_from_number" VARCHAR(50),
    "stringee_start_time" TIMESTAMP(6),
    "stringee_end_time" TIMESTAMP(6),
    "stringee_from_internal" INTEGER,
    "stringee_to_internal" INTEGER,
    "stringee_recorded" INTEGER,
    "video_call" INTEGER,
    "google_contacts" VARCHAR(255),
    "google_contacts_id" VARCHAR(255),
    "pulled_from_google_contacts" INTEGER,
    "is_primary_contact" INTEGER,
    "is_billing_contact" INTEGER,
    "links" JSONB,
    "phone_numbers" JSONB,
    "phone_nos" JSONB,
    "emails" JSONB,
    "database_created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "database_updated_at" TIMESTAMP(6),

    CONSTRAINT "contacts_pkey" PRIMARY KEY ("uuid")
);

-- CreateIndex
CREATE UNIQUE INDEX "contacts_name_key" ON "erpnext"."contacts"("name");

-- CreateIndex
CREATE INDEX "contacts_name_idx" ON "erpnext"."contacts"("name");
