-- CreateTable
CREATE TABLE "erpnext"."sales_orders" (
    "uuid" UUID NOT NULL,
    "name" TEXT,
    "owner" TEXT,
    "creation" TIMESTAMP(3),
    "modified" TIMESTAMP(3),
    "modified_by" TEXT,
    "docstatus" INTEGER,
    "idx" INTEGER,
    "title" TEXT,
    "naming_series" TEXT,
    "tax_id" TEXT,
    "order_type" TEXT,
    "skip_delivery_note" INTEGER,
    "delivery_date" TIMESTAMP(3),
    "po_no" TEXT,
    "po_date" TIMESTAMP(3),
    "company" TEXT,
    "amended_from" TEXT,
    "customer_name" TEXT,
    "order_number" TEXT,
    "transaction_date" TIMESTAMP(3),
    "real_order_date" TIMESTAMP(3),
    "cancelled_status" TEXT,
    "financial_status" TEXT,
    "fulfillment_status" TEXT,
    "expected_delivery_date" TIMESTAMP(3),
    "cost_center" TEXT,
    "project" TEXT,
    "currency" TEXT,
    "conversion_rate" DOUBLE PRECISION,
    "selling_price_list" TEXT,
    "price_list_currency" TEXT,
    "plc_conversion_rate" DOUBLE PRECISION,
    "ignore_pricing_rule" INTEGER,
    "scan_barcode" TEXT,
    "set_warehouse" TEXT,
    "reserve_stock" INTEGER,
    "apply_discount_on" TEXT,
    "base_discount_amount" DECIMAL(18,6),
    "coupon_code" TEXT,
    "additional_discount_percentage" DECIMAL(18,6),
    "total_qty" INTEGER,
    "total" DECIMAL(18,6),
    "discount_amount" DECIMAL(18,6),
    "grand_total" DECIMAL(18,6),
    "base_total" DECIMAL(18,6),
    "base_net_total" DECIMAL(18,6),
    "total_net_weight" DECIMAL(18,6),
    "net_total" DECIMAL(18,6),
    "tax_category" TEXT,
    "taxes_and_charges" TEXT,
    "shipping_rule" TEXT,
    "incoterm" TEXT,
    "named_place" TEXT,
    "base_total_taxes_and_charges" DECIMAL(18,6),
    "total_taxes_and_charges" DECIMAL(18,6),
    "base_grand_total" DECIMAL(18,6),
    "base_rounding_adjustment" DECIMAL(18,6),
    "base_rounded_total" DECIMAL(18,6),
    "base_in_words" TEXT,
    "rounding_adjustment" DECIMAL(18,6),
    "rounded_total" DECIMAL(18,6),
    "in_words" TEXT,
    "advance_paid" DECIMAL(18,6),
    "disable_rounded_total" INTEGER,
    "other_charges_calculation" TEXT,
    "contact_person" TEXT,
    "contact_display" TEXT,
    "contact_phone" TEXT,
    "contact_mobile" TEXT,
    "contact_email" TEXT,
    "customer_address" TEXT,
    "address_display" TEXT,
    "customer_group" TEXT,
    "territory" TEXT,
    "shipping_address_name" TEXT,
    "shipping_address" TEXT,
    "customer" TEXT,
    "gender" TEXT,
    "customer_type" TEXT,
    "customer_personal_id" TEXT,
    "birth_date" TIMESTAMP(3),
    "date_of_issuance" TIMESTAMP(3),
    "dispatch_address" TEXT,
    "place_of_issuance" TEXT,
    "dispatch_address_name" TEXT,
    "company_address" TEXT,
    "company_address_display" TEXT,
    "company_contact_person" TEXT,
    "status" TEXT,
    "delivery_status" TEXT,
    "per_delivered" DECIMAL(18,6),
    "per_billed" DECIMAL(18,6),
    "per_picked" DECIMAL(18,6),
    "billing_status" TEXT,
    "sales_partner" TEXT,
    "amount_eligible_for_commission" DECIMAL(18,6),
    "commission_rate" DECIMAL(18,6),
    "total_commission" DECIMAL(18,6),
    "loyalty_points" INTEGER,
    "loyalty_amount" DECIMAL(18,6),
    "from_date" TIMESTAMP(3),
    "to_date" TIMESTAMP(3),
    "auto_repeat" TEXT,
    "letter_head" TEXT,
    "group_same_items" INTEGER,
    "select_print_heading" TEXT,
    "language" TEXT,
    "is_internal_customer" INTEGER,
    "represents_company" TEXT,
    "source" TEXT,
    "inter_company_order_reference" TEXT,
    "campaign" TEXT,
    "party_account_currency" TEXT,
    "total_amount" DECIMAL(18,6),
    "expected_payment_date" TIMESTAMP(3),
    "paid_amount" DECIMAL(18,6),
    "balance" DECIMAL(18,6),
    "payment_terms_template" TEXT,
    "tc_name" TEXT,
    "terms" TEXT,
    "haravan_order_id" TEXT,
    "haravan_ref_order_id" TEXT,
    "haravan_created_at" TIMESTAMP(3),
    "source_name" TEXT,
    "sales_team" JSONB,
    "ref_sales_orders" JSONB,
    "promotions" JSONB,
    "product_categories" JSONB,
    "packed_items" JSONB,
    "taxes" JSONB,
    "pricing_rules" JSONB,
    "payment_records" JSONB,
    "payment_schedule" JSONB,
    "policies" JSONB,
    "items" JSONB,
    "database_created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "database_updated_at" TIMESTAMP(6),

    CONSTRAINT "sales_orders_pkey" PRIMARY KEY ("uuid")
);

-- CreateTable
CREATE TABLE "erpnext"."sales_order_items" (
    "uuid" UUID NOT NULL,
    "name" VARCHAR(140),
    "owner" VARCHAR(140),
    "creation" TIMESTAMP(6),
    "modified" TIMESTAMP(6),
    "modified_by" VARCHAR(140),
    "docstatus" SMALLINT,
    "idx" SMALLINT,
    "item_name" VARCHAR(200),
    "variant_title" VARCHAR(200),
    "sku" VARCHAR(140),
    "barcode" VARCHAR(140),
    "haravan_variant_id" BIGINT,
    "ensure_delivery_based_on_produced_serial_no" SMALLINT,
    "is_stock_item" SMALLINT,
    "reserve_stock" SMALLINT,
    "qty" INTEGER,
    "stock_uom" VARCHAR(50),
    "uom" VARCHAR(50),
    "conversion_factor" DECIMAL(18,6),
    "stock_qty" INTEGER,
    "stock_reserved_qty" INTEGER,
    "price_list_rate" DECIMAL(18,6),
    "base_price_list_rate" DECIMAL(18,6),
    "discount_percentage" DECIMAL(18,6),
    "discount_amount" DECIMAL(18,6),
    "distributed_discount_amount" DECIMAL(18,6),
    "base_rate_with_margin" DECIMAL(18,6),
    "margin_type" VARCHAR(50),
    "margin_rate_or_amount" DECIMAL(18,6),
    "rate_with_margin" DECIMAL(18,6),
    "rate" DECIMAL(18,6),
    "amount" DECIMAL(18,6),
    "base_rate" DECIMAL(18,6),
    "base_amount" DECIMAL(18,6),
    "stock_uom_rate" DECIMAL(18,6),
    "is_free_item" SMALLINT,
    "grant_commission" SMALLINT,
    "net_rate" DECIMAL(18,6),
    "net_amount" DECIMAL(18,6),
    "base_net_rate" DECIMAL(18,6),
    "base_net_amount" DECIMAL(18,6),
    "billed_amt" DECIMAL(18,6),
    "valuation_rate" DECIMAL(18,6),
    "gross_profit" DECIMAL(18,6),
    "delivered_by_supplier" SMALLINT,
    "weight_per_unit" DECIMAL(18,6),
    "total_weight" DECIMAL(18,6),
    "against_blanket_order" SMALLINT,
    "blanket_order_rate" DECIMAL(18,6),
    "actual_qty" INTEGER,
    "company_total_stock" INTEGER,
    "projected_qty" INTEGER,
    "ordered_qty" INTEGER,
    "planned_qty" INTEGER,
    "production_plan_qty" INTEGER,
    "work_order_qty" INTEGER,
    "delivered_qty" INTEGER,
    "produced_qty" INTEGER,
    "returned_qty" INTEGER,
    "picked_qty" INTEGER,
    "page_break" SMALLINT,
    "item_tax_rate" TEXT,
    "transaction_date" DATE,
    "cost_center" VARCHAR(140),
    "parent" VARCHAR(140),
    "parentfield" VARCHAR(140),
    "parenttype" VARCHAR(140),
    "doctype" VARCHAR(140),
    "database_created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "database_updated_at" TIMESTAMP(6),

    CONSTRAINT "sales_order_items_pkey" PRIMARY KEY ("uuid")
);

-- CreateTable
CREATE TABLE "erpnext"."sales_teams" (
    "uuid" UUID NOT NULL,
    "name" VARCHAR(140),
    "owner" VARCHAR(140),
    "creation" TIMESTAMP(6),
    "modified" TIMESTAMP(6),
    "modified_by" VARCHAR(140),
    "docstatus" SMALLINT,
    "idx" SMALLINT,
    "allocated_amount" DECIMAL(18,6),
    "allocated_percentage" DECIMAL(5,2),
    "commission_rate" VARCHAR(140),
    "incentive" DECIMAL(18,6),
    "parentfield" VARCHAR(140),
    "parent" VARCHAR(140),
    "parenttype" VARCHAR(140),
    "sales_person" VARCHAR(140),
    "database_created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "database_updated_at" TIMESTAMP(6),

    CONSTRAINT "sales_teams_pkey" PRIMARY KEY ("uuid")
);

-- CreateIndex
CREATE UNIQUE INDEX "sales_orders_name_key" ON "erpnext"."sales_orders"("name");

-- CreateIndex
CREATE UNIQUE INDEX "sales_order_items_name_key" ON "erpnext"."sales_order_items"("name");

-- CreateIndex
CREATE INDEX "sales_order_items_barcode_idx" ON "erpnext"."sales_order_items"("barcode");

-- CreateIndex
CREATE INDEX "sales_order_items_haravan_variant_id_idx" ON "erpnext"."sales_order_items"("haravan_variant_id");

-- CreateIndex
CREATE INDEX "sales_order_items_item_name_idx" ON "erpnext"."sales_order_items"("item_name");

-- CreateIndex
CREATE INDEX "sales_order_items_parent_idx" ON "erpnext"."sales_order_items"("parent");

-- CreateIndex
CREATE INDEX "sales_order_items_sku_idx" ON "erpnext"."sales_order_items"("sku");

-- CreateIndex
CREATE UNIQUE INDEX "sales_teams_name_key" ON "erpnext"."sales_teams"("name");
