export const DebounceActions = {
  SEND_TO_MESSAGE_SUMMARY_QUEUE: "SEND_TO_MESSAGE_SUMMARY_QUEUE",
  SEND_TO_MESSAGE_LAST_CUSTOMER_QUEUE: "SEND_TO_MESSAGE_LAST_CUSTOMER_QUEUE",
  SEND_TO_PANCAKE_EXTRA_HOOKS_QUEUE: "SEND_TO_PANCAKE_EXTRA_HOOKS_QUEUE",
  SEND_TO_HARAVAN_PRODUCT_QUEUE: "SEND_TO_HARAVAN_PRODUCT_QUEUE",
  SEND_TO_ERPNEXT_SALES_ORDER_QUEUE: "SEND_TO_ERPNEXT_SALES_ORDER_QUEUE"
};
