-- CreateTable
CREATE TABLE "marketing"."facebook_ads_adsets" (
    "uuid" UUID NOT NULL DEFAULT gen_random_uuid(),
    "id" TEXT NOT NULL,
    "campaign_id" TEXT NOT NULL,
    "account_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "status" TEXT,
    "configured_status" TEXT,
    "effective_status" TEXT,
    "daily_budget" TEXT,
    "lifetime_budget" TEXT,
    "budget_remaining" TEXT,
    "daily_min_spend_target" TEXT,
    "daily_spend_cap" TEXT,
    "lifetime_min_spend_target" TEXT,
    "lifetime_spend_cap" TEXT,
    "bid_amount" TEXT,
    "bid_strategy" TEXT,
    "bid_constraints" JSONB,
    "bid_info" JSONB,
    "billing_event" TEXT,
    "optimization_goal" TEXT,
    "optimization_sub_event" TEXT,
    "targeting" JSONB,
    "targeting_optimization_types" JSONB,
    "promoted_object" JSONB,
    "destination_type" TEXT,
    "start_time" TIMESTAMP(3),
    "end_time" TIMESTAMP(3),
    "adset_schedule" JSONB,
    "pacing_type" JSONB,
    "recurring_budget_semantics" BOOLEAN,
    "learning_stage_info" JSONB,
    "issues_info" JSONB,
    "is_dynamic_creative" BOOLEAN,
    "creative_sequence" JSONB,
    "attribution_spec" JSONB,
    "campaign_attribution" TEXT,
    "frequency_control_specs" JSONB,
    "adlabels" JSONB,
    "source_adset_id" TEXT,
    "dsa_beneficiary" TEXT,
    "dsa_payor" TEXT,
    "regional_regulated_categories" JSONB,
    "regional_regulation_identities" JSONB,
    "asset_feed_id" TEXT,
    "rf_prediction_id" TEXT,
    "review_feedback" TEXT,
    "use_new_app_click" BOOLEAN,
    "created_time" TIMESTAMP(3),
    "updated_time" TIMESTAMP(3),
    "campaign_active_time" TEXT,
    "synced_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "facebook_ads_adsets_pkey" PRIMARY KEY ("uuid")
);

-- CreateIndex
CREATE UNIQUE INDEX "facebook_ads_adsets_id_key" ON "marketing"."facebook_ads_adsets"("id");
