import dayjs from "dayjs";

export default class OrderMapper {
  static mapOrder(order) {
    const billingAddress = order.billing_address || {};
    const clientDetails = order.client_details || {};
    const customer = order.customer || {};
    const customerDefaultAddress = customer.default_address || {};
    const shippingAddress = order.shipping_address || {};

    return {
      id: order.id,
      billing_address_id: billingAddress.id ? BigInt(billingAddress.id) : null,
      billing_address_address1: billingAddress.address1,
      billing_address_address2: billingAddress.address2,
      billing_address_city: billingAddress.city,
      billing_address_company: billingAddress.company,
      billing_address_country: billingAddress.country,
      billing_address_first_name: billingAddress.first_name,
      billing_address_last_name: billingAddress.last_name,
      billing_address_phone: billingAddress.phone,
      billing_address_province: billingAddress.province,
      billing_address_zip: billingAddress.zip,
      billing_address_name: billingAddress.name,
      billing_address_province_code: billingAddress.province_code,
      billing_address_country_code: billingAddress.country_code,
      billing_address_default: billingAddress.default,
      billing_address_district: billingAddress.district,
      billing_address_district_code: billingAddress.district_code,
      billing_address_ward: billingAddress.ward,
      billing_address_ward_code: billingAddress.ward_code,
      browser_ip: order.browser_ip,
      buyer_accepts_marketing: order.buyer_accepts_marketing,
      cancel_reason: order.cancel_reason,
      cancelled_at: order.cancelled_at ? dayjs(order.cancelled_at).toDate() : null,
      cart_token: order.cart_token,
      checkout_token: order.checkout_token,
      client_details_accept_language: clientDetails.accept_language,
      client_details_browser_height: clientDetails.browser_height ? BigInt(clientDetails.browser_height) : null,
      client_details_browser_width: clientDetails.browser_width ? BigInt(clientDetails.browser_width) : null,
      client_details_session_hash: clientDetails.session_hash,
      client_details_user_agent: clientDetails.user_agent,
      client_details_browser_ip: clientDetails.browser_ip,
      closed_at: order.closed_at ? dayjs(order.closed_at).toDate() : null,
      created_at: order.created_at ? dayjs(order.created_at).toDate() : null,
      currency: order.currency,
      customer_id: customer.id ? BigInt(customer.id) : null,
      customer_email: customer.email,
      customer_phone: customer.phone,
      customer_first_name: customer.first_name,
      customer_last_name: customer.last_name,
      customer_multipass_identifier: customer.multipass_identifier,
      customer_last_order_id: customer.last_order_id ? BigInt(customer.last_order_id) : null,
      customer_last_order_name: order.customer_last_order_name,
      customer_note: order.customer_note,
      customer_order_count: customer.order_count,
      customer_state: customer.state,
      customer_tags: customer.tags,
      customer_total_spent: customer.total_spent,
      customer_updated_at: customer.updated_at ? dayjs(customer.updated_at).toDate() : null,
      customer_verified_email: customer.verified_email,
      customer_send_email_invite: customer.send_email_invite,
      customer_send_email_welcome: customer.send_email_welcome,
      customer_password: customer.password,
      customer_password_confirmation: customer.password_confirmation,
      customer_group_name: customer.group_name,
      customer_birthday: customer.birthday,
      customer_gender: String(customer?.gender) || null,
      customer_last_order_date: customer.last_order_date ? dayjs(customer.last_order_date).toDate() : null,
      customer_default_address_id: customerDefaultAddress.id ? BigInt(customerDefaultAddress.id) : null,
      customer_default_address_address1: customerDefaultAddress.address1,
      customer_default_address_address2: customerDefaultAddress.address2,
      customer_default_address_city: customerDefaultAddress.city,
      customer_default_address_company: customerDefaultAddress.company,
      customer_default_address_country: customerDefaultAddress.country,
      customer_default_address_province: customerDefaultAddress.province,
      customer_default_address_first_name: customerDefaultAddress.first_name,
      customer_default_address_last_name: customerDefaultAddress.last_name,
      customer_default_address_phone: customerDefaultAddress.phone,
      customer_default_address_province_code: customerDefaultAddress.province_code,
      customer_default_address_country_code: customerDefaultAddress.country_code,
      customer_default_address_default: customerDefaultAddress.default,
      customer_default_address_district: customerDefaultAddress.district,
      customer_default_address_district_code: customerDefaultAddress.district_code,
      customer_default_address_ward: customerDefaultAddress.ward,
      customer_default_address_ward_code: customerDefaultAddress.ward_code,
      discount_codes: order.discount_codes,
      email: order.email,
      financial_status: order.financial_status,
      fulfillment_status: order.fulfillment_status,
      tags: order.tags,
      gateway: order.gateway,
      gateway_code: order.gateway_code,
      landing_site: order.landing_site,
      landing_site_ref: order.landing_site_ref,
      source: order.source,
      name: order.name,
      note: order.note,
      number: order.number,
      order_number: order.order_number,
      processing_method: order.processing_method,
      shipping_address_address1: shippingAddress.address1,
      shipping_address_address2: shippingAddress.address2,
      shipping_address_city: shippingAddress.city,
      shipping_address_company: shippingAddress.company,
      shipping_address_country: shippingAddress.country,
      shipping_address_first_name: shippingAddress.first_name,
      shipping_address_last_name: shippingAddress.last_name,
      shipping_address_latitude: shippingAddress.latitude,
      shipping_address_longitude: shippingAddress.longitude,
      shipping_address_phone: shippingAddress.phone,
      shipping_address_province: shippingAddress.province,
      shipping_address_zip: shippingAddress.zip,
      shipping_address_name: shippingAddress.name,
      shipping_address_province_code: shippingAddress.province_code,
      shipping_address_country_code: shippingAddress.country_code,
      shipping_address_district_code: shippingAddress.district_code,
      shipping_address_district: shippingAddress.district,
      shipping_address_ward_code: shippingAddress.ward_code,
      shipping_address_ward: shippingAddress.ward,
      shipping_lines: order.shipping_lines,
      source_name: order.source_name,
      subtotal_price: order.subtotal_price,
      tax_lines: order.tax_lines,
      taxes_included: order.taxes_included,
      token: order.token,
      total_discounts: order.total_discounts,
      total_line_items_price: order.total_line_items_price,
      total_price: order.total_price,
      total_tax: order.total_tax,
      total_weight: order.total_weight,
      updated_at: order.updated_at ? dayjs(order.updated_at).toDate() : null,
      note_attributes: order.note_attributes,
      confirmed_at: order.confirmed_at ? dayjs(order.confirmed_at).toDate() : null,
      closed_status: order.closed_status,
      cancelled_status: order.cancelled_status,
      confirmed_status: order.confirmed_status,
      assigned_location_id: order.assigned_location_id ? BigInt(order.assigned_location_id) : null,
      assigned_location_name: order.assigned_location_name,
      assigned_location_at: order.assigned_location_at ? dayjs(order.assigned_location_at).toDate() : null,
      exported_confirm_at: order.exported_confirm_at ? dayjs(order.exported_confirm_at).toDate() : null,
      user_id: order.user_id ? BigInt(order.user_id) : null,
      device_id: order.device_id ? BigInt(order.device_id) : null,
      location_id: order.location_id ? BigInt(order.location_id) : null,
      location_name: order.location_name,
      ref_order_id: order.ref_order_id ? BigInt(order.ref_order_id) : null,
      ref_order_date: order.ref_order_date ? dayjs(order.ref_order_date).toDate() : null,
      ref_order_number: order.ref_order_number,
      utm_source: order.utm_source,
      utm_medium: order.utm_medium,
      utm_campaign: order.utm_campaign,
      utm_term: order.utm_term,
      utm_content: order.utm_content,
      payment_url: order.payment_url,
      contact_email: order.contact_email,
      order_processing_status: order.order_processing_status,
      prev_order_id: order.prev_order_id ? BigInt(order.prev_order_id) : null,
      prev_order_number: order.prev_order_number,
      prev_order_date: order.prev_order_date ? dayjs(order.prev_order_date).toDate() : null,
      redeem_model: order.redeem_model,
      confirm_user: order.confirm_user ? BigInt(order.confirm_user) : null,
      risk_level: order.risk_level,
      discount_applications: order.discount_applications
    };
  }

  static mapLineItem(item) {
    return {
      id: item.id,
      order_id: item.order_id,
      fulfillable_quantity: item.fulfillable_quantity,
      fulfillment_service: item.fulfillment_service,
      fulfillment_status: item.fulfillment_status,
      grams: item.grams,
      price: item.price,
      price_original: item.price_original,
      price_promotion: item.price_promotion,
      product_id: item.product_id ? BigInt(item.product_id) : null,
      quantity: item.quantity,
      requires_shipping: item.requires_shipping,
      sku: item.sku,
      title: item.title,
      variant_id: item.variant_id ? BigInt(item.variant_id) : null,
      variant_title: item.variant_title,
      vendor: item.vendor,
      type: item.type,
      name: item.name,
      gift_card: item.gift_card,
      taxable: item.taxable,
      tax_lines: item.tax_lines,
      product_exists: item.product_exists,
      barcode: item.barcode,
      properties: item.properties,
      total_discount: item.total_discount,
      applied_discounts: item.applied_discounts,
      image: item.image,
      not_allow_promotion: item.not_allow_promotion,
      ma_cost_amount: item.ma_cost_amount
    };
  }

  static mapTransaction(item) {
    return {
      id: item.id ? BigInt(item.id) : null,
      order_id: item.order_id ? BigInt(item.order_id) : null,
      amount: item.amount,
      authorization: item.authorization,
      created_at: item.created_at ? dayjs(item.created_at).toDate() : null,
      device_id: item.device_id ? BigInt(item.device_id) : null,
      gateway: item.gateway,
      kind: item.kind,
      receipt: item.receipt,
      status: item.status,
      test: item.test,
      user_id: item.user_id ? BigInt(item.user_id) : null,
      location_id: item.location_id ? BigInt(item.location_id) : null,
      currency: item.currency,
      is_cod_gateway: item.is_cod_gateway
    };
  }

  static mapFulfillment(item) {
    return {
      id: item.id ? BigInt(item.id) : null,
      order_id: item.order_id ? BigInt(item.order_id) : null,
      status: item.status,
      created_at: item.created_at ? dayjs(item.created_at).toDate() : null,
      updated_at: item.updated_at ? dayjs(item.updated_at).toDate() : null,
      tracking_company: item.tracking_company,
      tracking_company_code: item.tracking_company_code,
      tracking_numbers: item.tracking_numbers,
      tracking_number: item.tracking_number,
      tracking_url: item.tracking_url,
      tracking_urls: item.tracking_urls
    };
  }

  static mapRefund(item) {
    return {
      id: item.id ? BigInt(item.id) : null,
      order_id: item.order_id ? BigInt(item.order_id) : null,
      created_at: item.created_at ? dayjs(item.created_at).toDate() : null,
      note: item.note,
      refund_line_items: item.refund_line_items,
      restock: item.restock,
      user_id: item.user_id ? BigInt(item.user_id) : null,
      location_id: item.location_id ? BigInt(item.location_id) : null,
      transactions: item.transactions
    };
  }
}
