import { safeValue } from "src/services/utils/data-mappers";

export const mapContactsToDatabase = (contacts) => {
  return contacts.map((contact) => ({
    name: safeValue(contact.name, "string"),
    owner: safeValue(contact.owner, "string"),
    creation: safeValue(contact.creation, "date"),
    modified: safeValue(contact.modified, "date"),
    modified_by: safeValue(contact.modified_by, "string"),
    docstatus: safeValue(contact.docstatus, "number"),
    idx: safeValue(contact.idx, "number"),
    salutation: safeValue(contact.salutation, "string"),
    first_name: safeValue(contact.first_name, "string"),
    address: safeValue(contact.address, "string"),
    gender: safeValue(contact.gender, "string"),
    sync_with_google_contacts: safeValue(
      contact.sync_with_google_contacts,
      "number",
    ),
    middle_name: safeValue(contact.middle_name, "string"),
    full_name: safeValue(contact.full_name, "string"),
    last_name: safeValue(contact.last_name, "string"),
    user: safeValue(contact.user, "string"),
    inserted_at: safeValue(contact.inserted_at, "date"),
    updated_at: safeValue(contact.updated_at, "date"),
    haravan_customer_id: safeValue(contact.haravan_customer_id, "string"),
    lead_owner: safeValue(contact.lead_owner, "string"),
    source_group: safeValue(contact.source_group, "string"),
    source: safeValue(contact.source, "string"),
    status: safeValue(contact.status, "string"),
    designation: safeValue(contact.designation, "string"),
    phone: safeValue(contact.phone, "string"),
    email_id: safeValue(contact.email_id, "string"),
    mobile_no: safeValue(contact.mobile_no, "string"),
    company_name: safeValue(contact.company_name, "string"),
    image: safeValue(contact.image, "string"),
    source_name: safeValue(contact.source_name, "string"),
    type: safeValue(contact.type, "string"),
    first_message_time: safeValue(contact.first_message_time, "date"),
    last_message_time: safeValue(contact.last_message_time, "date"),
    phone_number_provided_time: safeValue(
      contact.phone_number_provided_time,
      "date",
    ),
    department: safeValue(contact.department, "string"),
    unsubscribed: safeValue(contact.unsubscribed, "number"),
    last_outgoing_call_time: safeValue(contact.last_outgoing_call_time, "date"),
    last_incoming_call_time: safeValue(contact.last_incoming_call_time, "date"),
    last_summarize_time: safeValue(contact.last_summarize_time, "date"),
    is_replied: safeValue(contact.is_replied, "number"),
    pancake_conversation_id: safeValue(
      contact.pancake_conversation_id,
      "string",
    ),
    pancake_inserted_at: safeValue(contact.pancake_inserted_at, "date"),
    pancake_updated_at: safeValue(contact.pancake_updated_at, "date"),
    pancake_customer_id: safeValue(contact.pancake_customer_id, "string"),
    thread_id: safeValue(contact.thread_id, "string"),
    psid: safeValue(contact.psid, "string"),
    can_inbox: safeValue(contact.can_inbox, "number"),
    pancake_page_id: safeValue(contact.pancake_page_id, "string"),
    custom_uuid: safeValue(contact.custom_uuid, "string"),
    page_url: safeValue(contact.page_url, "string"),
    user_agent: safeValue(contact.user_agent, "string"),
    remote_ip: safeValue(contact.remote_ip, "string"),
    form_id: safeValue(contact.form_id, "string"),
    form_name: safeValue(contact.form_name, "string"),
    form_inserted_at: safeValue(contact.form_inserted_at, "date"),
    form_updated_at: safeValue(contact.form_updated_at, "date"),
    stringee_id: safeValue(contact.stringee_id, "string"),
    stringee_to_number: safeValue(contact.stringee_to_number, "string"),
    stringee_from_number: safeValue(contact.stringee_from_number, "string"),
    stringee_start_time: safeValue(contact.stringee_start_time, "date"),
    stringee_end_time: safeValue(contact.stringee_end_time, "date"),
    stringee_from_internal: safeValue(contact.stringee_from_internal, "number"),
    stringee_to_internal: safeValue(contact.stringee_to_internal, "number"),
    stringee_recorded: safeValue(contact.stringee_recorded, "number"),
    video_call: safeValue(contact.video_call, "number"),
    google_contacts: safeValue(contact.google_contacts, "string"),
    google_contacts_id: safeValue(contact.google_contacts_id, "string"),
    pulled_from_google_contacts: safeValue(
      contact.pulled_from_google_contacts,
      "number",
    ),
    is_primary_contact: safeValue(contact.is_primary_contact, "number"),
    is_billing_contact: safeValue(contact.is_billing_contact, "number"),
    // JSON fields
    links: contact.links || null,
    phone_numbers: contact.phone_numbers || null,
    phone_nos: contact.phone_nos || null,
    emails: contact.emails || null,
  }));
};
