-- CreateTable
CREATE TABLE "misa"."loan_agreements" (
    "refid" UUID NOT NULL,
    "refno" VARCHAR(50),
    "credit_agreement_refid" UUID,
    "credit_agreement_refno" VARCHAR(100),
    "reftype" INTEGER,
    "account_object_id" UUID,
    "account_object_code" VARCHAR(50),
    "account_object_name" TEXT,
    "branch_id" UUID,
    "branch_name" TEXT,
    "disbursement_date" TIMESTAMPTZ(6),
    "due_date" TIMESTAMPTZ(6),
    "next_interest_payment_date" TIMESTAMPTZ(6),
    "next_principal_payment_date" TIMESTAMPTZ(6),
    "created_date" TIMESTAMPTZ(6),
    "modified_date" TIMESTAMPTZ(6),
    "currency_id" VARCHAR(10),
    "exchange_rate" DECIMAL(18,4) DEFAULT 1.0,
    "loan_value" DECIMAL(18,4) DEFAULT 0,
    "loan_value_exchange" DECIMAL(18,4) DEFAULT 0,
    "disbursed_value" DECIMAL(18,4) DEFAULT 0,
    "disbursed_value_exchange" DECIMAL(18,4) DEFAULT 0,
    "paid_principal" DECIMAL(18,4) DEFAULT 0,
    "paid_principal_exchange" DECIMAL(18,4) DEFAULT 0,
    "payable_interest" DECIMAL(18,4) DEFAULT 0,
    "paid_interest" DECIMAL(18,4) DEFAULT 0,
    "paid_interest_exchange" DECIMAL(18,4) DEFAULT 0,
    "current_credit_limit" DECIMAL(18,4) DEFAULT 0,
    "current_credit_limit_exchange" DECIMAL(18,4) DEFAULT 0,
    "principal_account" VARCHAR(20),
    "interest_account" VARCHAR(20),
    "beneficiary_account_id" UUID,
    "beneficiary_account" VARCHAR(100),
    "beneficiary_bank_name" TEXT,
    "interest_rate_now" DECIMAL(10,4) DEFAULT 0,
    "daily_interest_rate" DECIMAL(10,6) DEFAULT 0,
    "payment_period" INTEGER,
    "payment_period_unit" INTEGER,
    "payment_period_by_month" INTEGER,
    "payment_period_text" VARCHAR(100),
    "interest_rate_type" INTEGER,
    "adjusting_method" INTEGER,
    "principal_payment_period" INTEGER,
    "interest_payment_period" INTEGER,
    "payment_method" INTEGER,
    "disbursement_method" INTEGER,
    "loan_status" INTEGER,
    "is_facility_contract" BOOLEAN DEFAULT false,
    "facility_contract_type" INTEGER,
    "is_parent" BOOLEAN DEFAULT false,
    "is_bold" BOOLEAN DEFAULT false,
    "is_old" BOOLEAN DEFAULT false,
    "is_valid" BOOLEAN DEFAULT false,
    "state" INTEGER,
    "created_by" TEXT,
    "modified_by" TEXT,
    "edit_version" BIGINT,
    "auto_refno" BOOLEAN,
    "force_update" BOOLEAN,
    "is_created_from_old_db" BOOLEAN,

    CONSTRAINT "loan_agreements_pkey" PRIMARY KEY ("refid")
);
-- CreateIndex
CREATE INDEX "idx_loan_refno" ON "misa"."loan_agreements"("refno");
