-- CreateTable
CREATE TABLE "erpnext"."leads" (
    "uuid" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "owner" VARCHAR(255),
    "creation" TIMESTAMP(6),
    "modified" TIMESTAMP(6),
    "modified_by" VARCHAR(255),
    "docstatus" INTEGER,
    "idx" INTEGER,
    "naming_series" VARCHAR(255),
    "type" VARCHAR(255),
    "salutation" VARCHAR(255),
    "first_name" VARCHAR(255),
    "middle_name" VARCHAR(255),
    "territory" VARCHAR(255),
    "lead_stage" VARCHAR(100),
    "phone" VARCHAR(20),
    "email_id" VARCHAR(255),
    "job_title" VARCHAR(255),
    "last_name" VARCHAR(255),
    "gender" VARCHAR(10),
    "qualified_lead_date" TIMESTAMP(6),
    "first_reach_at" TIMESTAMP(6),
    "lead_owner" VARCHAR(255),
    "source" VARCHAR(255),
    "status" VARCHAR(50),
    "customer" VARCHAR(255),
    "request_type" VARCHAR(100),
    "lead_name" VARCHAR(255),
    "lead_received_date" TIMESTAMP(6),
    "lead_source_name" VARCHAR(255),
    "lead_source_platform" VARCHAR(255),
    "qualification_status" VARCHAR(255),
    "qualified_by" VARCHAR(255),
    "qualified_on" TIMESTAMP(6),
    "purpose_lead" VARCHAR(255),
    "expected_delivery_date" DATE,
    "budget_lead" VARCHAR(255),
    "province" VARCHAR(255),
    "region" VARCHAR(255),
    "company_name" VARCHAR(255),
    "no_of_employees" VARCHAR(20),
    "annual_revenue" DECIMAL,
    "industry" VARCHAR(255),
    "market_segment" VARCHAR(255),
    "fax" VARCHAR(255),
    "tax_number" VARCHAR(255),
    "ceo_name" VARCHAR(255),
    "birth_date" DATE,
    "address" TEXT,
    "personal_tax_id" VARCHAR(255),
    "first_channel" VARCHAR(255),
    "personal_id" VARCHAR(255),
    "place_of_issuance" VARCHAR(255),
    "date_of_issuance" DATE,
    "website" VARCHAR(255),
    "bank_name" VARCHAR(255),
    "bank_branch" VARCHAR(255),
    "account_number" VARCHAR(255),
    "bank_province" VARCHAR(255),
    "bank_district" VARCHAR(255),
    "bank_ward" VARCHAR(255),
    "campaign_name" VARCHAR(255),
    "company" VARCHAR(255),
    "website_from_data" VARCHAR(255),
    "language" VARCHAR(10),
    "image" TEXT,
    "title" VARCHAR(255),
    "disabled" INTEGER,
    "unsubscribed" INTEGER,
    "blog_subscriber" INTEGER,
    "mobile_no" VARCHAR(20),
    "whatsapp_no" VARCHAR(20),
    "phone_ext" VARCHAR(20),
    "check_duplicate" VARCHAR(255),
    "doctype" VARCHAR(50),
    "notes" JSONB,
    "user_tags" VARCHAR(255),
    "database_updated_at" TIMESTAMP(6),
    "preferred_product_type" JSONB,
    "database_created_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "leads_pkey" PRIMARY KEY ("uuid")
);

-- CreateIndex
CREATE UNIQUE INDEX "leads_name_key" ON "erpnext"."leads"("name");

-- CreateIndex
CREATE INDEX "leads_name_idx" ON "erpnext"."leads"("name");
