import { safeValue } from "src/services/utils/data-mappers";

export const mapLeadsToDatabase = (leads) => {
  return leads.map((lead) => ({
    name: lead.name || null,
    owner: lead.owner || null,
    creation: lead.creation ? new Date(lead.creation) : null,
    modified: lead.modified ? new Date(lead.modified) : null,
    modified_by: lead.modified_by || null,
    docstatus: lead.docstatus || 0,
    idx: lead.idx || null,
    title: lead.title || null,
    naming_series: lead.naming_series || null,
    type: safeValue(lead.type),
    salutation: safeValue(lead.salutation),
    first_name: safeValue(lead.first_name),
    middle_name: safeValue(lead.middle_name),
    territory: safeValue(lead.territory),
    lead_stage: safeValue(lead.lead_stage),
    phone: safeValue(lead.phone),
    email_id: safeValue(lead.email_id),
    job_title: safeValue(lead.job_title),
    last_name: safeValue(lead.last_name),
    gender: safeValue(lead.gender),
    qualified_lead_date: lead.qualified_lead_date
      ? new Date(lead.qualified_lead_date)
      : null,
    first_reach_at: lead.first_reach_at ? new Date(lead.first_reach_at) : null,
    lead_owner: safeValue(lead.lead_owner),
    source: safeValue(lead.source),
    status: safeValue(lead.status),
    customer: safeValue(lead.customer),
    request_type: safeValue(lead.request_type),
    lead_name: safeValue(lead.lead_name),
    lead_received_date: lead.lead_received_date
      ? new Date(lead.lead_received_date)
      : null,
    lead_source_name: safeValue(lead.lead_source_name),
    lead_source_platform: safeValue(lead.lead_source_platform),
    qualification_status: safeValue(lead.qualification_status),
    qualified_by: safeValue(lead.qualified_by),
    qualified_on: lead.qualified_on ? new Date(lead.qualified_on) : null,
    purpose_lead: safeValue(lead.purpose_lead),
    expected_delivery_date: lead.expected_delivery_date
      ? new Date(lead.expected_delivery_date)
      : null,
    budget_lead: safeValue(lead.budget_lead),
    province: safeValue(lead.province),
    region: safeValue(lead.region),
    company_name: safeValue(lead.company_name),
    no_of_employees: safeValue(lead.no_of_employees),
    annual_revenue: safeValue(lead.annual_revenue),
    industry: safeValue(lead.industry),
    market_segment: safeValue(lead.market_segment),
    fax: safeValue(lead.fax),
    tax_number: safeValue(lead.tax_number),
    ceo_name: safeValue(lead.ceo_name),
    birth_date: lead.birth_date ? new Date(lead.birth_date) : null,
    address: safeValue(lead.address),
    personal_tax_id: safeValue(lead.personal_tax_id),
    first_channel: safeValue(lead.first_channel),
    personal_id: safeValue(lead.personal_id),
    place_of_issuance: safeValue(lead.place_of_issuance),
    date_of_issuance: lead.date_of_issuance
      ? new Date(lead.date_of_issuance)
      : null,
    website: safeValue(lead.website),
    bank_name: safeValue(lead.bank_name),
    bank_branch: safeValue(lead.bank_branch),
    account_number: safeValue(lead.account_number),
    bank_province: safeValue(lead.bank_province),
    bank_district: safeValue(lead.bank_district),
    bank_ward: safeValue(lead.bank_ward),
    campaign_name: safeValue(lead.campaign_name),
    company: safeValue(lead.company),
    website_from_data: safeValue(lead.website_from_data),
    language: safeValue(lead.language),
    image: safeValue(lead.image),
    disabled: safeValue(lead.disabled),
    unsubscribed: safeValue(lead.unsubscribed),
    blog_subscriber: safeValue(lead.blog_subscriber),
    mobile_no: safeValue(lead.mobile_no),
    whatsapp_no: safeValue(lead.whatsapp_no),
    phone_ext: safeValue(lead.phone_ext),
    check_duplicate: lead.check_duplicate || null,
    // data from child table
    preferred_product_type: lead.preferred_product_type || null,
    doctype: lead.doctype || null,
    notes: lead.notes || null,
    user_tags: lead.user_tags || null
  }));
};
