-- CreateTable
CREATE TABLE "misa"."pending_loan_agreements" (
    "refid" UUID NOT NULL,
    "refno" VARCHAR(50),
    "account_object_id" UUID,
    "account_object_code" VARCHAR(50),
    "account_object_name" TEXT,
    "description" TEXT,
    "branch_id" UUID,
    "branch_name" TEXT,
    "disbursement_date" TIMESTAMPTZ(6),
    "due_date" TIMESTAMPTZ(6),
    "next_interest_receiving_date" TIMESTAMPTZ(6),
    "next_principal_receiving_date" TIMESTAMPTZ(6),
    "lending_value" DECIMAL(18,4) DEFAULT 0,
    "exchange_rate" DECIMAL(18,4) DEFAULT 1.0,
    "lending_value_exchange" DECIMAL(18,4) DEFAULT 0,
    "disbursed_value" DECIMAL(18,4) DEFAULT 0,
    "disbursed_value_exchange" DECIMAL(18,4) DEFAULT 0,
    "principal_account" VARCHAR(20),
    "interest_account" VARCHAR(20),
    "disbursement_method" INTEGER,
    "received_principal" DECIMAL(18,4) DEFAULT 0,
    "received_principal_exchange" DECIMAL(18,4) DEFAULT 0,
    "receivable_interest" DECIMAL(18,4) DEFAULT 0,
    "received_interest" DECIMAL(18,4) DEFAULT 0,
    "received_interest_exchange" DECIMAL(18,4) DEFAULT 0,
    "current_credit_limit" DECIMAL(18,4) DEFAULT 0,
    "current_credit_limit_exchange" DECIMAL(18,4) DEFAULT 0,
    "receiving_period" INTEGER,
    "receiving_period_unit" INTEGER,
    "receiving_period_by_month" INTEGER,
    "receiving_period_text" VARCHAR(100),
    "receiving_method" INTEGER,
    "interest_rate_type" INTEGER,
    "daily_interest_rate" DECIMAL(10,6) DEFAULT 0,
    "adjusting_method" INTEGER,
    "principal_receiving_period" INTEGER,
    "interest_receiving_period" INTEGER,
    "currency_id" VARCHAR(10),
    "interest_rate_now" DECIMAL(10,4) DEFAULT 0,
    "is_facility_contract" BOOLEAN DEFAULT false,
    "facility_contract_type" INTEGER,
    "is_parent" BOOLEAN DEFAULT false,
    "is_bold" BOOLEAN DEFAULT false,
    "is_old" BOOLEAN DEFAULT false,
    "is_valid" BOOLEAN DEFAULT false,
    "lending_status" INTEGER,
    "excel_row_index" INTEGER,
    "state" INTEGER,
    "reftype" INTEGER,
    "created_date" TIMESTAMPTZ(6),
    "created_by" TEXT,
    "modified_date" TIMESTAMPTZ(6),
    "modified_by" TEXT,
    "edit_version" BIGINT,
    "auto_refno" BOOLEAN,
    "force_update" BOOLEAN,
    "is_created_from_old_db" BOOLEAN,

    CONSTRAINT "pending_loan_agreements_pkey" PRIMARY KEY ("refid")
);

-- CreateIndex
CREATE INDEX "idx_pending_loan_refno" ON "misa"."pending_loan_agreements"("refno");
