-- CreateTable
CREATE TABLE "erpnext"."customers" (
    "uuid" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "owner" VARCHAR(255),
    "creation" TIMESTAMP(6),
    "modified" TIMESTAMP(6),
    "modified_by" VARCHAR(255),
    "docstatus" INTEGER,
    "idx" INTEGER,
    "naming_series" VARCHAR(255),
    "salutation" VARCHAR(255),
    "customer_name" VARCHAR(255),
    "customer_group" VARCHAR(255),
    "bizfly_customer_number" VARCHAR(255),
    "is_internal_customer" INTEGER,
    "customer_type" VARCHAR(255),
    "customer_rank" VARCHAR(255),
    "account_manager" VARCHAR(255),
    "lead_name" VARCHAR(255),
    "opportunity_name" VARCHAR(255),
    "territory" VARCHAR(255),
    "prospect_name" VARCHAR(255),
    "company_name" VARCHAR(255),
    "no_of_employees" INTEGER,
    "industry" VARCHAR(255),
    "market_segment" VARCHAR(255),
    "tax_number" VARCHAR(255),
    "ceo_name" VARCHAR(255),
    "personal_document_type" VARCHAR(255),
    "birth_date" TIMESTAMP(6),
    "gender" VARCHAR(255),
    "personal_id" VARCHAR(255),
    "place_of_issuance" VARCHAR(255),
    "person_name" VARCHAR(255),
    "date_of_issuance" TIMESTAMP(6),
    "first_source" VARCHAR(255),
    "customer_website" VARCHAR(255),
    "customer_journey" VARCHAR(255),
    "default_currency" VARCHAR(255),
    "default_bank_account" VARCHAR(255),
    "default_price_list" VARCHAR(255),
    "represents_company" INTEGER,
    "customer_pos_id" VARCHAR(255),
    "website" VARCHAR(255),
    "language" VARCHAR(255),
    "customer_details" VARCHAR(255),
    "customer_primary_address" VARCHAR(255),
    "primary_address" VARCHAR(1024),
    "image" VARCHAR(255),
    "customer_primary_contact" VARCHAR(255),
    "primary_contact" VARCHAR(255),
    "mobile_no" VARCHAR(255),
    "email_id" VARCHAR(255),
    "phone" VARCHAR(255),
    "invoice_type" VARCHAR(255),
    "vat_email" VARCHAR(255),
    "vat_name" VARCHAR(255),
    "vat_address" VARCHAR(255),
    "personal_tax_id" VARCHAR(255),
    "bank_account" VARCHAR(255),
    "payment_terms" VARCHAR(255),
    "loyalty_program" VARCHAR(255),
    "loyalty_program_tier" VARCHAR(255),
    "rank" VARCHAR(255),
    "purchase_amount_last_12_months" DECIMAL(18,6),
    "rank_expired_date" TIMESTAMP(6),
    "priority_login_date" TIMESTAMP(6),
    "cumulative_revenue" DECIMAL(18,6),
    "cashback" DECIMAL(18,6),
    "true_cumulative_revenue" DECIMAL(18,6),
    "withdraw_cashback" DECIMAL(18,6),
    "referrals_revenue" DECIMAL(18,6),
    "pending_cashback" DECIMAL(18,6),
    "priority_bank_account" VARCHAR(255),
    "default_sales_partner" VARCHAR(255),
    "default_commission_rate" DECIMAL(18,6),
    "so_required" INTEGER,
    "dn_required" INTEGER,
    "is_frozen" INTEGER,
    "disabled" SMALLINT,
    "haravan_id" VARCHAR(255),
    "bizfly_id" VARCHAR(255),
    "tax_id" VARCHAR(255),
    "tax_category" VARCHAR(255),
    "tax_withholding_category" VARCHAR(255),
    "account" JSONB,
    "portal_users" JSONB,
    "companies" JSONB,
    "sales_team" JSONB,
    "coupon_table" JSONB,
    "credit_limits" JSONB,
    "database_created_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "database_updated_at" TIMESTAMP(6),

    CONSTRAINT "customers_pkey" PRIMARY KEY ("uuid")
);

-- CreateIndex
CREATE UNIQUE INDEX "customers_name_key" ON "erpnext"."customers"("name");

-- CreateIndex
CREATE INDEX "customers_name_idx" ON "erpnext"."customers"("name");

-- CreateIndex
CREATE INDEX "customers_customer_name_idx" ON "erpnext"."customers"("customer_name");

-- CreateIndex
CREATE INDEX "customers_haravan_id_idx" ON "erpnext"."customers"("haravan_id");
