DROP EXTENSION IF EXISTS "timescaledb" CASCADE;
CREATE EXTENSION IF NOT EXISTS "timescaledb";

DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP EXTENSION IF EXISTS "vector" CASCADE;
CREATE EXTENSION IF NOT EXISTS "vector";
