-- CreateTable
CREATE TABLE "misa"."sales_detail_report" (
    "ref_detail_id" UUID NOT NULL,
    "session_id" UUID,
    "detail_id" INTEGER,
    "refid" UUID,
    "sync_session_id" UUID NOT NULL,
    "posted_date" TIMESTAMPTZ(6),
    "refdate" TIMESTAMPTZ(6),
    "inv_date" TIMESTAMPTZ(6),
    "refno" TEXT,
    "inv_no" TEXT,
    "journal_memo" TEXT,
    "description" TEXT,
    "account_object_id" UUID,
    "account_object_code" TEXT,
    "account_object_name" TEXT,
    "account_object_address" TEXT,
    "account_object_tax_code" TEXT,
    "tel" TEXT,
    "contact_name" TEXT,
    "inventory_item_id" UUID,
    "inventory_item_code" TEXT,
    "inventory_item_name" TEXT,
    "inventory_item_category_code" TEXT,
    "inventory_item_category_name" TEXT,
    "stock_code" TEXT,
    "stock_name" TEXT,
    "unit_name" TEXT,
    "sale_quantity" DECIMAL(19,4),
    "sale_amount" DECIMAL(19,4),
    "unit_price" DECIMAL(19,4),
    "cost_amount" DECIMAL(19,4),
    "cost_unit_price" DECIMAL(19,4),
    "discount_amount" DECIMAL(19,4),
    "vat_amount" DECIMAL(19,4),
    "receipt_amount" DECIMAL(19,4),
    "debit_account" TEXT,
    "credit_account" TEXT,
    "cost_account" TEXT,
    "stock_account" TEXT,
    "master_custom_field1" TEXT,
    "master_custom_field2" TEXT,
    "master_custom_field3" TEXT,
    "master_custom_field4" TEXT,
    "custom_field1" TEXT,
    "reftype" INTEGER,
    "reftype_name" TEXT,
    "branch_id" UUID,
    "branch_name" TEXT,
    "currency_id" TEXT,
    "updated_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sales_detail_report_pkey" PRIMARY KEY ("ref_detail_id")
);

-- CreateIndex
CREATE INDEX "idx_sales_posted_date" ON "misa"."sales_detail_report"("posted_date");
