export const ERPNEXT_PAYMENT_METHODS = {
  CASH: "Cash",
  COD: "Cash On Delivery",
  PAYMENT_LINK: "Payment Link",
  POS: "POS",
  WIRE_TRANSFER: "Wire Transfer",
  QR: "QR"
};

/**
 * Internal Vietnamese payment type names
 */
export const INTERNAL_PAYMENT_TYPES = {
  CASH: "Tiền Mặt",
  COD: "COD HTC",
  PAYMENT_LINK: "Cà Thẻ Online",
  POS: "Cà Thẻ Tại Cửa Hàng",
  WIRE_TRANSFER: "QR",
  QR: "QR"
};

export const PAYMENT_METHOD_MAPPING = {
  [ERPNEXT_PAYMENT_METHODS.CASH]: INTERNAL_PAYMENT_TYPES.CASH,
  [ERPNEXT_PAYMENT_METHODS.COD]: INTERNAL_PAYMENT_TYPES.COD,
  [ERPNEXT_PAYMENT_METHODS.PAYMENT_LINK]: INTERNAL_PAYMENT_TYPES.PAYMENT_LINK,
  [ERPNEXT_PAYMENT_METHODS.POS]: INTERNAL_PAYMENT_TYPES.POS,
  [ERPNEXT_PAYMENT_METHODS.WIRE_TRANSFER]: INTERNAL_PAYMENT_TYPES.WIRE_TRANSFER,
  [ERPNEXT_PAYMENT_METHODS.QR]: INTERNAL_PAYMENT_TYPES.QR
};

export const QR_PAYMENT_METHODS = [
  ERPNEXT_PAYMENT_METHODS.WIRE_TRANSFER,
  ERPNEXT_PAYMENT_METHODS.QR
];

export const MANUAL_PAYMENT_METHODS = [
  ERPNEXT_PAYMENT_METHODS.CASH,
  ERPNEXT_PAYMENT_METHODS.COD,
  ERPNEXT_PAYMENT_METHODS.PAYMENT_LINK,
  ERPNEXT_PAYMENT_METHODS.POS
];

export const TRANSFER_STATUS = {
  CONFIRMED: "Xác nhận",
  PENDING: "Chờ",
  CREATING: "Đang tạo",
  REFUND: "Đơn hoàn trả",
  CANCELLED: "Hủy"
};

