export function rawToPaymentEntry(body) {
  return {
    amended_from: body.amended_from,
    apply_tax_withholding_amount: body.apply_tax_withholding_amount,
    auto_repeat: body.auto_repeat,
    bank: body.bank,
    bank_account: body.bank_account,
    bank_account_branch: body.bank_account_branch,
    bank_account_no: body.bank_account_no,
    bank_details: body.bank_details ? {
      bank_bin: body.bank_details.bank_bin,
      bank_code: body.bank_details.bank_code,
      bank_name: body.bank_details.bank_name,
      swift_number: body.bank_details.swift_number
    } : null,
    bank_transactions: body.bank_transactions,
    base_in_words: body.base_in_words,
    base_paid_amount: body.base_paid_amount,
    base_paid_amount_after_tax: body.base_paid_amount_after_tax,
    base_received_amount: body.base_received_amount,
    base_received_amount_after_tax: body.base_received_amount_after_tax,
    base_total_allocated_amount: body.base_total_allocated_amount,
    base_total_taxes_and_charges: body.base_total_taxes_and_charges,
    book_advance_payments_in_separate_party_account: body.book_advance_payments_in_separate_party_account,
    clearance_date: body.clearance_date,
    company: body.company,
    contact_email: body.contact_email,
    contact_person: body.contact_person,
    cost_center: body.cost_center,
    created_by_display: body.created_by_display,
    creation: body.creation,
    custom_remarks: body.custom_remarks,
    custom_transaction_id: body.custom_transaction_id,
    custom_transfer_note: body.custom_transfer_note,
    custom_transfer_status: body.custom_transfer_status,
    customer_details: body.customer_details
      ? {
        mobile_no: body.customer_details.mobile_no,
        name: body.customer_details.name,
        phone: body.customer_details.phone
      }
      : null,
    deductions: body.deductions,
    difference_amount: body.difference_amount,
    docstatus: body.docstatus,
    doctype: body.doctype,
    idx: body.idx,
    in_words: body.in_words,
    is_opening: body.is_opening,
    letter_head: body.letter_head,
    misa_sync_error_msg: body.misa_sync_error_msg,
    misa_sync_guid: body.misa_sync_guid,
    misa_synced: body.misa_synced,
    misa_synced_at: body.misa_synced_at,
    mode_of_payment: body.mode_of_payment,
    modified: body.modified,
    modified_by: body.modified_by,
    name: body.name,
    name_display: body.name_display,
    naming_series: body.naming_series,
    owner: body.owner,
    paid_amount: body.paid_amount,
    paid_amount_after_tax: body.paid_amount_after_tax,
    paid_from: body.paid_from,
    paid_from_account_balance: body.paid_from_account_balance,
    paid_from_account_currency: body.paid_from_account_currency,
    paid_from_account_type: body.paid_from_account_type,
    paid_to: body.paid_to,
    paid_to_account_balance: body.paid_to_account_balance,
    paid_to_account_currency: body.paid_to_account_currency,
    paid_to_account_type: body.paid_to_account_type,
    party: body.party,
    party_balance: body.party_balance,
    party_bank_account: body.party_bank_account,
    party_name: body.party_name,
    party_type: body.party_type,
    payment_date: body.payment_date,
    payment_order: body.payment_order,
    payment_order_status: body.payment_order_status,
    payment_type: body.payment_type,
    posting_date: body.posting_date,
    print_heading: body.print_heading,
    project: body.project,
    purchase_taxes_and_charges_template: body.purchase_taxes_and_charges_template,
    qr_url: body.qr_url,
    received_amount: body.received_amount,
    received_amount_after_tax: body.received_amount_after_tax,
    reconcile_on_advance_payment_date: body.reconcile_on_advance_payment_date,
    reference_date: body.reference_date,
    reference_no: body.reference_no,
    references: body.references || [],
    remarks: body.remarks,
    sales_taxes_and_charges_template: body.sales_taxes_and_charges_template,
    source_exchange_rate: body.source_exchange_rate,
    status: body.status,
    target_exchange_rate: body.target_exchange_rate,
    tax_withholding_category: body.tax_withholding_category,
    taxes: body.taxes,
    title: body.title,
    total_allocated_amount: body.total_allocated_amount,
    total_order_amount: body.total_order_amount,
    total_taxes_and_charges: body.total_taxes_and_charges,
    unallocated_amount: body.unallocated_amount,
    verified_by: body.verified_by,
    gateway: body.gateway,
    payment_code: body.payment_code,
    custom_webhook_processed: body.custom_webhook_processed
  };
}

export function rawToReference(ref) {
  return {
    account: ref.account,
    account_type: ref.account_type,
    allocated_amount: ref.allocated_amount,
    balance: ref.balance,
    bill_no: ref.bill_no,
    creation: ref.creation,
    docstatus: ref.docstatus,
    doctype: ref.doctype,
    due_date: ref.due_date,
    exchange_gain_loss: ref.exchange_gain_loss,
    exchange_rate: ref.exchange_rate,
    idx: ref.idx,
    modified: ref.modified,
    modified_by: ref.modified_by,
    name: ref.name,
    order_number: ref.order_number,
    outstanding_amount: ref.outstanding_amount,
    owner: ref.owner,
    parent: ref.parent,
    parentfield: ref.parentfield,
    parenttype: ref.parenttype,
    payment_request: ref.payment_request,
    payment_request_outstanding: ref.payment_request_outstanding,
    payment_term: ref.payment_term,
    payment_term_outstanding: ref.payment_term_outstanding,
    payment_type: ref.payment_type,
    reconcile_effect_on: ref.reconcile_effect_on,
    reference_doctype: ref.reference_doctype,
    reference_name: ref.reference_name,
    split_order_group_name: ref.split_order_group_name,
    total_amount: ref.total_amount,
    sales_order_details: ref.sales_order_details
      ? {
        haravan_cancelled_status: ref.sales_order_details.haravan_cancelled_status,
        haravan_financial_status: ref.sales_order_details.haravan_financial_status,
        haravan_order_id: ref.sales_order_details.haravan_order_id,
        haravan_order_number: ref.sales_order_details.haravan_order_number
      }
      : null
  };
}

export const PaymentOrderStatus = {
  PENDING: "Pending",
  SUCCESS: "Success",
  CANCEL: "Cancel"
};

export const PaymentEntryStatus = {
  PENDING: "pending",
  SUCCESS: "success",
  CANCEL: "cancel"
};
